[package]
name = "shapely"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.14", default-features = false, features = [
  "bevy_asset", "bevy_audio", "bevy_core_pipeline",
  "bevy_render", "bevy_sprite", "bevy_text", "bevy_ui", "bevy_winit",
  "default_font", "multi_threaded", "png", "wav", "webgl2"
] }
bevy_rapier2d = { version = "0.27", features = ["simd-stable"] }
getrandom = { version = "0.3", features = ["wasm_js"] }
uuid = { version = "1", features = ["js"] }
pathfinding = "4.16"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[profile.release]
codegen-units = 1
lto = "thin"
